Exam/Grestau.Web/Models/ErrorViewModel.cs
namespace Grestau.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Exam/Grestau.Web/Controllers/RestaurantsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Grestau.Data.Services;

namespace Grestau.Web
{
    public partial class RestaurantsController : Controller
    {
        private readonly RestaurantService _restaurantService = new RestaurantService();
        private readonly AdressService _adressService = new AdressService();
        private readonly RatingService _ratingService = new RatingService();
        private readonly DataService _dataService = new DataService();

        /// <summary>
        /// Get details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = _restaurantService.GetRestaurantById((Guid) id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        /// <summary>
        /// Get index 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View(_restaurantService.GetAllRestaurant());
        }

        /// <summary>
        /// Get Home Page
        /// </summary>
        /// <returns></returns>
        public IActionResult Home()
        {
            return View(_restaurantService.GetTopFiveRestaurant());
        }

        /// <summary>
        /// Get ratings page
        /// </summary>
        /// <returns></returns>
        public IActionResult Ratings()
        {
            return View(_restaurantService.GetAllRestaurant());
        }
    }
}

Exam/Grestau.Web/Views/Restaurants/Create.cshtml
@model Grestau.Data.Model.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <h5>Info</h5>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control"/>
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <hr>
            <h5>Address</h5>
            <div class="form-group">
                <label asp-for="Adress.Numero" class="control-label"></label>
                <input asp-for="Adress.Numero" class="form-control"/>
                <span asp-validation-for="Adress.Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress.Rue" class="control-label"></label>
                <input asp-for="Adress.Rue" class="form-control"/>
                <span asp-validation-for="Adress.Rue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress.CodePostal" class="control-label"></label>
                <input asp-for="Adress.CodePostal" class="form-control"/>
                <span asp-validation-for="Adress.CodePostal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress.Ville" class="control-label"></label>
                <input asp-for="Adress.Ville" class="form-control"/>
                <span asp-validation-for="Adress.Ville" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Exam/Grestau.Web/Views/Restaurants/Data.cshtml
@{
    ViewData["Title"] = "Data Management";
}

<h1>Data Management</h1>

<h4>Import Data from json</h4>
@using (Html.BeginForm("Data", "Restaurants", FormMethod.Post))
{
    <form method="post">
        <!--<input type="file" name="file">-->
        <textarea name="dataraw" rows="10" cols="75" placeholder="Paste your json here"></textarea>
        <br>
        <input type="submit" class="btn btn-primary" value="Import data" accept="application/json">
    </form>
}
<hr/>
<h4>Export Data to json</h4>
<a class="btn btn-primary" asp-action="saveData">Export Data</a>
<hr/>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Exam/Grestau.Web/Views/Restaurants/Delete.cshtml
@model Grestau.Data.Model.Restaurant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress.Numero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress.Numero)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress.Rue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress.Rue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress.Ville)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress.Ville)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress.CodePostal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress.CodePostal)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Exam/Grestau.Web/Views/Restaurants/Details.cshtml
@model Grestau.Data.Model.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress.Numero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress.Numero)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress.Rue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress.Rue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress.Ville)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress.Ville)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress.CodePostal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress.CodePostal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Exam/Grestau.Web/Views/Restaurants/Edit.cshtml
@model Grestau.Data.Model.Restaurant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Restaurant</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <h5>Info</h5>
            <input type="hidden" asp-for="ID"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control"/>
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <hr>
            <h5>Address</h5>
            <input type="hidden" asp-for="Adress.ID"/>
            <div class="form-group">
                <label asp-for="Adress.Numero" class="control-label"></label>
                <input asp-for="Adress.Numero" class="form-control"/>
                <span asp-validation-for="Adress.Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress.Rue" class="control-label"></label>
                <input asp-for="Adress.Rue" class="form-control"/>
                <span asp-validation-for="Adress.Rue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress.Ville" class="control-label"></label>
                <input asp-for="Adress.Ville" class="form-control"/>
                <span asp-validation-for="Adress.Ville" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress.CodePostal" class="control-label"></label>
                <input asp-for="Adress.CodePostal" class="form-control"/>
                <span asp-validation-for="Adress.CodePostal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Exam/Grestau.Web/Views/Restaurants/Home.cshtml
@model IEnumerable<Grestau.Data.Model.Restaurant>

@{
    ViewData["Title"] = "Home";
}

<h1>Home</h1>

<p>Bienvenue sur Grestau, la meilleur platform pour les restau de grenoble</p>
<h3>Top 5 restau a grenoble ! </h3>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adress)
        </th>
        <th>
            Date Last Visite
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating.Stars)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @{
                    var fullAdress = item.Adress.Numero + " " + item.Adress.Rue + " " + item.Adress.CodePostal + " " + item.Adress.Ville;
                    @Html.DisplayFor(m => fullAdress)
                }
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Rating.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating.Stars)
            </td>
        </tr>
    }
    </tbody>
</table>

Exam/Grestau.Web/Views/Restaurants/Index.cshtml
@model IEnumerable<Grestau.Data.Model.Restaurant>

@{
    ViewData["Title"] = "Index";
}

<h1>Restaurant</h1>

<p>
    <a asp-action="Create">Create New</a> | <a asp-action="Ratings">Edit Ratings</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adress)
        </th>
        <th>
            Date Last Visite
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating.Stars)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @{
                    var fullAdress = item.Adress.Numero + " " + item.Adress.Rue + " " + item.Adress.CodePostal + " " + item.Adress.Ville;
                    @Html.DisplayFor(m => fullAdress)
                    ;
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating.Stars)
            </td>
            <td>
              <!-- <a asp-action="Rating" asp-route-id="@item.ID">Edit Rating</a> -->
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Exam/Grestau.Web/Views/Restaurants/Rating.cshtml
@model Grestau.Data.Model.Restaurant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Rating</h4>
<hr/>
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Phone)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Phone)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Description)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Email)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Email)
    </dd>
    <dt class="col-sm-2">
         @Html.DisplayNameFor(model => model.Adress)
    </dt>
    <dd class="col-sm-10">
        @{
            var fullAdress = Model.Adress.Numero + " " + Model.Adress.Rue + " " + Model.Adress.CodePostal + " " + Model.Adress.Ville;
            @Html.DisplayFor(m => fullAdress)
        }
    </dd>

    <!--
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Adress.Numero)
    </dt>
    <dd class="col-sm-10">
    @Html.DisplayFor(model => model.Adress.Numero)
    
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Adress.Rue)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Adress.Rue)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Adress.Ville)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Adress.Ville)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Adress.CodePostal)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Adress.CodePostal)
    </dd>
    -->
</dl>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Rating">
            <input type="hidden" asp-for="ID"/>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Rating.ID"/>
            <div class="form-group">
                <label asp-for="Rating.Date" class="control-label">Date Last Visite</label>
                <input type="date" asp-for="Rating.Date" class="form-control"/>
                <span asp-validation-for="Rating.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating.Stars" class="control-label"></label>
                <input asp-for="Rating.Stars" class="form-control"/>
                <span asp-validation-for="Rating.Stars" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating.Comment" class="control-label"></label>
                <textarea rows="10" cols="100" asp-for="Rating.Comment" class="form-control"></textarea>
                <span asp-validation-for="Rating.Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Ratings">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Exam/Grestau.Web/Views/Restaurants/Ratings.cshtml
@model IEnumerable<Grestau.Data.Model.Restaurant>

@{
    ViewData["Title"] = "Ratings";
}

<h1>Restaurant Ratings</h1>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Date Last Visite
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating.Stars)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating.Comment)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.Rating.Date)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.Rating.Stars)
            </th>
            <th>
                @{
                    if (item.Rating?.Comment != null)
                    {
                        var comment = item.Rating.Comment.Substring(0, item.Rating.Comment.Length > 31 ? 31 : item.Rating.Comment.Length);
                        if (comment.Length > 30)
                        {
                            comment += "...";
                        }
                        @Html.DisplayFor(m => comment)
                    }
                }
            </th>
            <td>
                <a asp-action="Rating" asp-route-id="@item.ID">Edit Rating</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Exam/Grestau.Web/Views/Restaurants/TopFive.cshtml
@model IEnumerable<Grestau.Data.Model.Restaurant>

@{
    ViewData["Title"] = "Top 5 restaurants";
}

<h1>Top 5 restaurants</h1>

<table class="table">
    <thead>
    <tr>
        <th>Rank</th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating.Stars)
        </th>

    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.Rating.Stars)
            </th>
        </tr>
    }
    </tbody>
</table>

Exam/Grestau.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Grestau.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Restaurants" asp-action="Index">Grestau.Web</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Home">Top 5</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Index">Restaurant</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Data">Import / Export</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Grestau.Web
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>